# ——————————————————————————————————————————————————————————————————————
# ПОДКЛЮЧЕНИЕ К БД
# ——————————————————————————————————————————————————————————————————————
database:
  type: sqlite # sqlite или mysql
  mysql:
    host: localhost
    port: 3306
    database: marry_db
    username: root
    password: ''

# ——————————————————————————————————————————————————————————————————————
# Настройки плагина
# ——————————————————————————————————————————————————————————————————————
settings:
  marriage-symbol: "❤" # Символ, который будет у пар по умолчанию при регистрации брака
  default-pvp-allowed: false # Разрешено ли пвп между супругами (Работает до изменения режима командой /marry pvp)
  list-items-per-page: 10 # Сколько пар выводить на одной странице (/marry list)
  broadcast-divorce: true  # Писать ли всем игрокам на сервере, когда кто-то разводится?
  tp-delay: 3 # Задержка перед телепортацией (время стоять на месте)

# ——————————————————————————————————————————————————————————————————————
# Настройки задержек (Cooldowns)
# Время указывается в секундах.
# Если поставить 0, задержка будет отключена.
# ——————————————————————————————————————————————————————————————————————
cooldowns:
  send: 30        # Предложение руки и сердца
  kiss: 10        # Поцелуй
  gift: 30        # Отправка подарка
  phrase: 10      # Случайная фраза партнеру
  tp: 300         # Телепорт к партнеру (/marry tp)
  home: 60        # Телепорт на точку дома (/marry home)
  sethome: 600    # Установка точки дома (/marry sethome)
  color: 10       # Смена цвета ника
  symbol: 10      # Смена символа пары
  status: 10      # Переключение уведомлений (вход/выход)
  pvp: 10         # Переключение режима PvP
  list: 2         # Просмотр списка всех браков
  bank: 5         # Операции с банком (вклад/снятие)

# ——————————————————————————————————————————————————————————————————————
# Список фраз для команды /marry phrase
# Можно добавлять свои, они будут выбираться случайно
# ——————————————————————————————————————————————————————————————————————
phrases:
  - "Ты — мое утреннее солнце, которое освещает даже самые пасмурные дни."
  - "Каждый миг, проведенный с тобой, — это как сладкая мелодия, звучащая в сердце."
  - "В твоих глазах я вижу отражение бесконечности и тепла."
  - "Ты — моя вдохновляющая муза, без которой мир был бы серым и скучным."
  - "Каждый раз, когда ты улыбаешься, у меня на душе становится легче."
  - "Любовь к тебе делает меня сильнее, открывает передо мной новые горизонты."
  - "Без тебя моя жизнь была бы, как книга без страниц — пустой и неинтересной."
  - "Твои нежные слова согревают мою душу, как теплый плед."
  - "Твоя улыбка — моё вдохновение, мой уют и покой."
  - "Ты — мелодия в сердце, стремительная и нежная."
  - "В каждом взгляде твоём я вижу целый мир."
  - "Ты — мой компас, который всегда указывает путь к счастью."
  - "Любовь к тебе — это вечный огонь, согревающий душу."
  - "Ты — мой самый драгоценный дар, который не купишь."
  - "Наша связь — крепче всякой нити, что соединяет сердца."
  - "Ты — причина моего счастливого смеха и ярких мечтаний."
  - "Твой голос — это музыка, которая звучит в моей душе."
  - "С тобой время летит незаметно."
  - "Ты – моя мечта, ставшая реальностью."
  - "Ты – самый красивый момент в моей жизни."
  - "В твоих глазах я нахожу дом."
  - "Без тебя мир кажется пустым."
  - "Только с тобой я могу быть собой."
  - "Люблю за каждое мгновение, проведенное с тобой."
  - "Я ценю тебя больше, чем слова могут сказать."
  - "Мне с тобой очень комфортно."
  - "Ты чудо."
  - "Я обожаю тебя, солнышко."
  - "Я рядом буду до конца."
  - "Мне становится легче от мыслей о тебе."
  - "У тебя безумно красивая улыбка, улыбайся чаще."
  - "Ты прелесть."
  - "Счастье это - ты."
  - "Я хочу находиться в твоих объятиях 24/7."

# ——————————————————————————————————————————————————————————————————————
# Доступные имена цветов для команды /marry color
# Игрок может написать название или HEX-код
# ——————————————————————————————————————————————————————————————————————
marry-colors:
  RED: "#FF5555"
  GREEN: "#55FF55"
  BLUE: "#5555FF"
  YELLOW: "#FFFF55"
  WHITE: "#FFFFFF"
  AQUA: "#55FFFF"
  PINK: "#FF69B4"
  PURPLE: "#AA00AA"
  GOLD: "#FFAA00"

# ——————————————————————————————————————————————————————————————————————
# Доступные имена символов для команды /marry symbol
# ——————————————————————————————————————————————————————————————————————
marry-symbols:
  HEART: "❤"
  STAR: "★"
  RING: "💍"
  FLOWER: "✿"